# Generated by Django 4.2 on 2023-08-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='job_site_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_active',
            field=models.BooleanField(default=True),
        ),
    ]
