# Generated by Django 4.2 on 2023-08-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0002_job_job_active_jobsite_job_site_active_task_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='active',
            new_name='task_active',
        ),
    ]
